# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ $.Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "webhook.certificate.name" . }}  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: {{ $.Release.Namespace }}
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
    - {{ template "webhook.service.name" . }}.{{ $.Release.Namespace }}.svc
    - {{ template "webhook.service.name" . }}.{{ $.Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ template "webhook.secret.name" . }} # this secret will not be prefixed, since it's not managed by kustomize
