---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lets-encrypt-issuer.yaml
  - self-signed-issuer.yaml
  - self-signed-cert.yaml
  - nifi-issuer.yaml
  - namespace.yaml