apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dex-client
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: dex
      app.kubernetes.io/instance: dex
      app.kubernetes.io/name: dex
  ingress:
    - from:
        - podSelector:
            matchLabels:
              dex-client: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: dex
              app.kubernetes.io/instance: dex
              app.kubernetes.io/name: dex
      ports:
        - port: 32000
          protocol: TCP
        - port: 5556
          protocol: TCP
---