# permissions for end users to view nifiresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nifiresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nifikop
    app.kubernetes.io/part-of: nifikop
    app.kubernetes.io/managed-by: kustomize
  name: nifiresource-viewer-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiresources/status
  verbs:
  - get
