apiVersion: v1
description: A Helm chart for NiFiKop - the Konpyūtāika NiFi Kubernetes operator
name: nifikop
home: https://github.com/konpyutaika/nifikop
sources:
  - https://github.com/konpyutaika/nifikop
version: 1.8.0
appVersion: 1.8.0-release
icon: https://konpyutaika.github.io/nifikop/img/nifikop.png
maintainers:
  - name: erdrix
    email: guittonalexandre@outlook.fr
keywords:
  - operator
  - nifi
  - nifikop
  - data
