apiVersion: nifi.orange.com/v1alpha1
kind: NifiDataflow
metadata:
  name: dataflow-lifecycle
spec:
  # the UUID of the parent process group where you want to deploy your dataflow, if not set deploy at root level.
  parentProcessGroupID: "16cfd2ec-0174-1000-0000-00004b9b35cc"
  # the UUID of the Bucket containing the flow.
  bucketId: "01ced6cc-0378-4893-9403-f6c70d080d4f"
  # the UUID of the flow to run.
  flowId: "9b2fb465-fb45-49e7-94fe-45b16b642ac9"
  # the version of the flow to run, if not present or equals to -1, then the latest version of flow will be used.
  flowVersion: 2
  # if the flow will be ran once or continuously checked
  syncMode: always
  # whether the flow is considered as ran if some controller services are still invalid or not.
  skipInvalidControllerService: true
  #  whether the flow is considered as ran if some components are still invalid or not.
  skipInvalidComponent: true
  # contains the reference to the NifiCluster with the one the dataflow is linked.
  clusterRef:
    name: nc
    namespace: nifikop
  # contains the reference to the NifiRegistry with the one the dataflow is linked.
  registryClientRef:
    name: squidflow
    namespace: nifikop
  # contains the reference to the ParameterContext with the one the dataflow is linked.
  parameterContextRef:
    name: dataflow-lifecycle
    namespace: nifikop
  # describes the way the operator will deal with data when a dataflow will be updated : drop or drain
  updateStrategy: drain
