apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-nginx-conf
  namespace: nifi
data:
  default.conf: |
    server {
        listen 443 ssl;

        server_name myserver.example.com;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        # use your context path here
        location /nifidev/ {
            proxy_pass https://nifikop:443/;   # rewrites /nifidev/* â†’ /* for NiFi
            proxy_ssl_server_name on;

            # NiFi proxy headers
            proxy_set_header X-ProxyScheme $scheme;
            proxy_set_header X-ProxyHost $host;
            proxy_set_header X-ProxyPort $server_port;
            proxy_set_header X-ProxyContextPath /nifidev;
            proxy_set_header X-ProxiedEntitiesChain CN=nginx-proxy;

            # Preserve Host for NiFi validation
            proxy_set_header Host nifi-internal.test.com;

            # Forward client IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }